---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: redis
    app.kubernetes.io/part-of: cabs
    app.openshift.io/runtime: redis
  name: redis
  namespace: demo
spec:
  containers:
  - image: docker.io/redis/redis-stack-server
    name: redis
    ports:
    - containerPort: 6379
      protocol: TCP
    - containerPort: 8001
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: demo
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
